fix: Reorder Dockerfile to copy mohtion/ before pip install
Hatchling requires the mohtion/ directory to exist before running
pip install -e . in order to build the package.

Moved 'COPY mohtion/ mohtion/' before 'RUN pip install' to fix:
ValueError: Unable to determine which files to ship inside the wheel.
The most likely cause is that there is no directory that matches
the name of your project (mohtion).